### ISSUE TITLE
Propose moving Test lists and Enable Test bool to a config file

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/ci-jenkins-pipelines#93]
As a third party user, I will tend to have a different test list than what is in [build_base_file.groovy](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/1a4acb80e65b6cab141398a162523973b3b618e0/pipelines/build/common/build_base_file.groovy#L70). I will also not necessarily want to follow changes made to ENABLE_TESTS such as https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/92. I am proposing we move these values into a configuration file so that users can point to their own config file.

**Comment by M-Davies** [comment]
Ref:
https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/bb2ada1e00694a18a00060d8ee37fb36b7f38a75/pipelines/build/common/build_base_file.groovy#L219-L223
and the test field of [#data fields](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines#data-fields):
| Name                       | Required? | Type                              | <div style="width:500px">Description</div> |
| :------------------------- | :---: | :------------------------------------ | :----------------------------------------- |
| test                       | ❌    | `String`<br>**OR**<br>`Map<String, List>`   | Tests to run against the binary after the build has completed. A `default` tag indicates that you want to run [whatever the default test nightly/release list is](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/ab947ce6ab0ecd75ebfb95eb2f75facb83e4dc13/pipelines/build/common/build_base_file.groovy#L66-L88).<br><br>Otherwise, you can [specify your own list for that paticular platform (not variant)](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/blob/ab947ce6ab0ecd75ebfb95eb2f75facb83e4dc13/pipelines/jobs/configurations/jdk16_pipeline_config.groovy#L59-L64) |

There shouldn't be a need to specify a new config parameter if we already have one that appears to do what you are describing regarding specifying your own tests.

> I will also not necessarily want to follow changes made to ENABLE_TESTS

That however is something that should be moved into a config file. I will look into this

**Comment by AdamBrousseau** [comment]
>There shouldn't be a need to specify a new config parameter if we already have one that appears to do what you are describing regarding specifying your own tests.

This feature is useful if you have an odd spec that does not follow the default. However for my use, all my specs run the same testing but that list does not match the Adopt default. I would therefore need to paste my list into every spec which is inconvenient. Moving that default list into defaults.json for example, would allow me to change it to my liking for all specs at once. Both for the Nightly and Weekly lists.

**Comment by AdamBrousseau** [comment]
Thanks, Morgan!
